### ISSUE TITLE
Text rendering disappears with scrolling in some options

### ISSUE THREAD

**Issue by Monkey3072** [Nippaku-Zanmu/meteor-translation-addon#1]
### **Some information**
Operating system: Windows 11 Family Chinese Version
Java version: Zulu-21.0.4
Minecraft version: 1.21 (Fabric)
Meteor Client version: v0.5.8
Other mods (if used): sodium, Litematica (and its dependencies, malilib) and Xearo's woeld map.

### **Steps to reproduce**

1. Switch the game language to Chinese.
2. Open Tracers-Entities window (As an example, other similar windows also have this issue) in the meteor GUI.
3. Scroll down the scroll wheel, and the text will appear at the bottom of the screen and then disappear.

https://github.com/user-attachments/assets/15ac4ca6-af3a-420d-891e-39f5c9e46a73

### **checklist**

- [x] This bug wasn't already reported.
- [ ] This is a valid bug (At least I saw it)
- [x] I have not used any OwO's or UwU's in this issue.

**Comment by Nippaku-Zanmu** [comment]
请开启流星端的自定义字体渲染 我只修改了流星端的自定义字体渲染 使其能够载入中文字体 对于mc的字体渲染我是无能为力的

The following is a machine rollover
Please enable custom font rendering on Meteor. I only modified the custom font rendering on Meteor to load Chinese fonts. There is nothing I can do about mc's font rendering

**Comment by Monkey3072** [comment]
非常好方案，使我的问题解决
